### ISSUE TITLE
Baby steps mode

### ISSUE THREAD

**Issue by mbirtwell** [JonJagger/cyber-dojo#52]
Hi Jon,

I did a session on cyber dojo today with a small group (thanks for all the work you've put in to it); we got to talking about other fun variations we could do and some one mentioned the baby steps approach. Normally you're only allowed to commit when green and if you run out of time and the tests are red you have to revert to the last commit. I was thinking it would probably be possible to add support for this to cyber dojo.

I was wondering what you thought of such a feature and whether if I tried to implement it you would consider a pull request for it?

I was thinking it would probably get enabled in sub-menu of the setup page (call it gimics or games or something). The length of the timer would be configurable there. The timer would get reset every time you went green and if it expired prompt (force) you to revert to the last green point.

I've not really looked at how this would fit in to the code yet. So I thought I'd better ask if there are any particular approaches you think I should take?

**Comment by JonJagger** [comment]
Hi Mike,
I'm not familiar with the rules of 'baby steps' ...
Could you explain them to me please? In detail.
Then I can try to answer your question better.
Cheers
Jon



On Tue, Jan 13, 2015 at 11:08 PM, Mike Birtwell <notifications@github.com>
wrote:

> Hi Jon,
>
> I did a session on cyber dojo today with a small group (thanks for all the
> work you've put in to it); we got to talking about other fun variations we
> could do and some one mentioned the baby steps approach. Normally you're
> only allowed to commit when green and if you run out of time and the tests
> are red you have to revert to the last commit. I was thinking it would
> probably be possible to add support for this to cyber dojo.
>
> I was wondering what you thought of such a feature and whether if I tried
> to implement it you would consider a pull request for it?
>
> I was thinking it would probably get enabled in sub-menu of the setup page
> (call it gimics or games or something). The length of the timer would be
> configurable there. The timer would get reset every time you went green and
> if it expired prompt (force) you to revert to the last green point.
>
> I've not really looked at how this would fit in to the code yet. So I
> thought I'd better ask if there are any particular approaches you think I
> should take?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JonJagger/cyber-dojo/issues/52>.
>



-- 
Cyber-Dojo : a place to practise the collaborative game called software
development.
Server at http://www.cyber-dojo.org
Open-sourced at http://github.com/JonJagger/cyberdojo
Explained at http://jonjagger.blogspot.co.uk/p/cyber-dojo_2380.html
Video of Roman Numerals kata in Ruby at https://vimeo.com/104548135

**Comment by mbirtwell** [comment]
So normally it runs something like this:

select a kata and set up source control for it.
start the timer
     start some activity either write a failing test and then write some code or start refactoring
     if the timer expires
          revert all your code since your last commit and re-start the timer
     if you finish the activity you started and all your tests green
          commit your code and re-start the timer
repeat until you finish the kata or your practice session ends.

There should be no breaks between the timer expiring or you committing and restarting the timer for discussion. Although it is acceptable for a pair to decide they'd rather spend a timer period discussing things than coding.

**Comment by JonJagger** [comment]
Hi Mike,
ok. understand. I was confused by the fact that cyber-dojo stores a commit
every time an animal presses the [test] button. So you would have to get a
commit (and traffic-light) to know if your tests were green...

I have put similarish 'external' features into cyber-dojo in the past.
For example, a timer which opened a dialog say "its time to rotate pair
partners".
And then removed them. I now feel strongly that such features are best
implemented by mechanisms outside of cyber-dojo. So I would probably not
pull this feature if you implemented it. But read on...

Technically it might be doable. But I don't think it would be that easy
because of the way cyber-dojo works. The [test] button page does not have a
"poll" into the server.
If the time-period start-time was on the server (and maybe shared between
all animals) a poll would have to be introduced.
If the timer was in the browser then it could easily be defeated by a
participant simply refreshing their page. A participant could always simply
revert to their previous green commit if not green when the timer went
(following the baby-steps rules) and then, as their first act in the new
period, simply revert back to their most recent red traffic-light before
the timeout. Viz, it would be trivial for them to defeat the system.

If I was going to try to introduce this feature I would do it as a control
from the dashboard.
The dashboard does have a 10 second poll.
A history-diff dialog opened from a traffic-light on the dashboard does not
currently allow a revert. But one could be introduced and then an automated
revert coded up somehow.

However, I do see value in the dashboard simply showing different
time-periods as "vertical stripes". The person running the dojo (the
sensei) would then keep an eye on this. This could also be useful as a
reminder if you wanted to rotate partners every period too. I would not
make the duration of the stripe a property of the dojo, rather I would make
it a property of the dashboard display which could be altered at will by
editing, eg a text input field.

Hope this helps.
Cheers
Jon



On Tue, Jan 13, 2015 at 11:30 PM, Mike Birtwell <notifications@github.com>
wrote:

> So normally it runs something like this:
>
> select a kata and set up source control for it.
> start the timer
> start some activity either write a failing test and then write some code
> or start refactoring
> if the timer expires
> revert all your code since your last commit and re-start the timer
> if you finish the activity you started and all your tests green
> commit your code and re-start the timer
> repeat until you finish the kata or your practice session ends.
>
> There should be no breaks between the timer expiring or you committing and
> restarting the timer for discussion. Although it is acceptable for a pair
> to decide they'd rather spend a timer period discussing things than coding.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JonJagger/cyber-dojo/issues/52#issuecomment-69842742>.
>



-- 
Cyber-Dojo : a place to practise the collaborative game called software
development.
Server at http://www.cyber-dojo.org
Open-sourced at http://github.com/JonJagger/cyberdojo
Explained at http://jonjagger.blogspot.co.uk/p/cyber-dojo_2380.html
Video of Roman Numerals kata in Ruby at https://vimeo.com/104548135

**Comment by mbirtwell** [comment]
I think for baby steps it's important that each animal's timer runs
independently.

I don't think the technical issues you raise are insurmountable. I would
probably run the timer in the browser but have it's start point set by the
server on a page load. I think you rely on participants joining in with
spirit of the exercise anyway, so I'm too worried about making it
impossible to defeat.

However this is all rather moot if you don't think this kind of feature is
good fit for cyber dojo.

I think the feature you described in the last two paragraphs sounds
interesting but I think it's a fundamentally different feature from the one
that I originally proposed. And I'm not sufficiently interested in that at
the moment to work on it my self.

Thank you for looking at this,

Mike
