### ISSUE TITLE
split Rust code 

### ISSUE THREAD

**Issue by JonJagger** [JonJagger/cyber-dojo#72]
The initial files for Rust are actually just one file, hiker.rs
I'd like this split into two files, hiker.rs containing answer() and
hiker.test.rs containing the test.
How do you do this?
What incantations do you need in cyber-dojo.sh?

**Comment by wimh** [comment]
From the [rust style guide][1]:
> Unit tests should live in a tests submodule at the bottom of the module they test.

Having said that, here are two ways to use separate files. 

### 1 separate module

Create a hikertest module which includes the hiker module. The filename will determine the modulename. Compile the hikertest module (assuming a filename ...test.rs). 

```rust
//hiker.rs
pub fn answer() -> i32 {
    6 * 9
}
```

```rust
//hikertest.rs
mod hiker;
use hiker::*;

#[test]
fn life_the_universe_and_everything() {
    assert_eq!(42, answer());
}
```

```sh
#cyber-dojo.sh
rustc --test -o run.tests *test.rs && ./run.tests
```

### 2 use cargo with a integration test

Creat a `Cargo.toml` file, include the name of the lib and the name of the test file. `cargo test` will perform all tests. This will also test documentation, so I added an example. (but this is probably not useful for cyberdojo). 
Default filenames cannot be used, because they require a `src` and `test` subdirectory. So the filenames must be defined in the `Cargo.toml`.
An integration test, can only test the public interface of the create it tests. So if submodules are used, they must be made public.

```toml
#Cargo.toml
[package]
name = "hiker"
version = "0.1.0"
authors = ["someone <someone@email.com>"]

[lib]
name = "hiker"
path = "hiker.rs"

[[test]]
name = "hikertest"
path = "hikertest.rs"
```

```rust
//hiker.rs

/// Returns an answer
///
/// # Examples
/// ```
/// use hiker::answer;
///
/// let n = answer();
/// assert_eq!(42, n);
/// ```
pub fn answer() -> i32 {
    6 * 9
}
```

```rust
//hikertest.rs
extern crate hiker;
use hiker::*;

#[test]
fn life_the_universe_and_everything() {
    assert_eq!(42, answer());
}
```

```sh
#cyber-dojo.sh
cargo test
```

Note that `cargo test` will also test a tests submodule at the bottom of the module if it exists...

 [1]: https://doc.rust-lang.org/style/testing/unit.html

**Comment by JonJagger** [comment]
Excellent. Many thanks. I have used the simpler first solution.
